### ISSUE TITLE
Checks for < 0 of unsigned variables.

### ISSUE THREAD

**Issue by brtnfld** [hpc-io/vol-async#14]
One of many checks do this comparision: 

   if ((attempt_count = check_app_acquire_mutex(task, &mutex_count, &acquired)) < 0)
        goto done;

is a no-op because attempt_count  is an unsigned int. This if condition can be removed.

**Comment by houjun** [comment]
@brtnfld If you look at check_app_acquire_mutex function, there are cases when it returns -1, e.g. lines 2984, 2995, etc. So the check should be there.

**Comment by brtnfld** [comment]
Should not _attempt_count_ be an 'int' instead if it can be negative?

**Comment by houjun** [comment]
OK, I see the problem, just pushed a fix
