### ISSUE TITLE
2.1 Compile H5_DIR Configure Issue

### ISSUE THREAD

**Issue by jahidhasanlinix** [hpc-io/vol-async#20]
Dear Authors, @houjun @jeanbez I was trying to compile 2.1 but had an issue once I run the second command which is
`> ./configure --prefix=$H5_DIR/install --enable-parallel --enable-threadsafe --enable-unsupported #(may need to add CC=cc or CC=mpicc)`
I tried with both, also I added some flags to make it work but it gives me errors. ./autogen.sh works but it does not generate any make file to compile as well.
Two different errors while adding `CC=cc` or `CC=mpicc`
I added some flags like `--with-zlib CFLAGS="03"` in some cases, I followed this link but still, it did not resolve my issue, not sure what blocking me to execute it successfully: [Link:](https://forums.developer.nvidia.com/t/help-configuring-hdf5-with-nvhpc-no-version-information-available/183413/4)

![Screenshot 2022-03-15 160746](https://user-images.githubusercontent.com/36171973/158664836-93b452c2-6aba-415e-aa94-69d51834910e.png)
![Screenshot 2022-03-15 160553](https://user-images.githubusercontent.com/36171973/158664839-83675749-3007-4d33-83a7-637f001b2bf9.png)

[2.2 works fine 
2.3 Fixed but can't `make` it as H5 is required]

I tried figuring it out but I really need a bit of suggestion or help to debug it.

Any suggestions will be highly appreciated, Thank you.

**Comment by houjun** [comment]
Looks like your mpicc is not working, can you try compiling a simple [MPI program](https://mpitutorial.com/tutorials/mpi-hello-world/) to see if it works?

**Comment by jahidhasanlinix** [comment]
@houjun Thank you so much. Its resolved now.
