### ISSUE TITLE
both ASYNC dynamic and static libraries in LDFLAGS in test/Makefile, conflict?

### ISSUE THREAD

**Issue by alvarovm** [hpc-io/vol-async#3]
Hi,
This is just a comment of an issue I found in the test/Makefile

Got this error while I was running the tests `async_test_serial.exe`
```
./async_test_serial.exe: symbol lookup error: /home/myuser/hdf5-async/vol-async/src/libh5async.so: undefined symbol: ABT_initialized
```

I noticed that LDFLAGS in the test/Makefile has:
```
LDFLAGS = $(DEBUG) -L$(ASYNC_DIR) -L$(ABT_DIR)/lib -L$(HDF5_DIR)/lib -Wl,-rpath=$(ASYNC_DIR) -Wl,-rpath=$(ABT_DIR)/lib -Wl,-rpath=$(HDF5_DIR)/lib -labt -lhdf5 -lh5async -lasynchdf5 -labt
```
So I removed '-lh5async' in LDFLAGS which is pointing to the dynamic library. Now the test  `async_test_serial.exe` passed.

**Comment by qkoziol** [comment]
Argobots (https://www.argobots.org) is a dependency for building this package.   Please build it and update the Makefile for where you have installed it.

**Comment by alvarovm** [comment]
I have Argobots in /home/myuser/hdf5-async/vol-async/argobots/
