### ISSUE TITLE
error when using H5S_BLOCK

### ISSUE THREAD

**Issue by wkliao** [hpc-io/vol-async#32]
Using Async I/O VOL version 1.4 and H5S_BLOCK as a memory space
will cause errors below.
```
 HDF5-DIAG: Error detected in HDF5 (1.13.3) MPI-process 0:
   #000: ../../hdf5-1.13.3/src/H5S.c line 487 in H5Scopy(): not a dataspace
     major: Invalid arguments to routine
     minor: Inappropriate type
   [ASYNC ABT LOG] Argobots execute async_dataset_write_fn failed
 free(): invalid pointer
 Abort (core dumped)
```
Here is a short test program to reproduce.
https://github.com/DataLib-ECP/vol-log-based/blob/master/tests/basic/h5s_block.c

**Comment by houjun** [comment]
Hi @wkliao, thanks for the bug report, I just pushed a fix to the develop branch that should fix this issue, could you give it a try?

**Comment by wkliao** [comment]
Just now tried it and It runs fine. Thanks.
